package org.example.proyectoprogramacion3fx.Model.vehiculos;

public enum MarcaVehiculoMoto {
    YAMAHA, HONDA, SUZUKI, HARLEY_DAVIDSON, UMA_BAJAJ, KAWASAKI, DUCATI, BMW_MOTORRAD, TRIUMPH, KTM,
    APRILLIA, ROYAL_ENFIELD, INDIAN_MOTORCYCLE, MV_AGUSTA, HUSQVARNA, MOTO_GUZZI, PIAGGIO,
    BENELLI, VESPA, GASGAS, ZERO_MOTORCYCLES, CFMOTO, BIMOTA, NORTON, SYM, LAMBRETTA, HERO_MOTOCORP,
    TVS_MOTOR_COMPANY, SWM, AJP, BUELL, HUSABERG, SHERCO, DERBI, GILERA, MONTESA, CAN_AM, BRAMMO, ALTA_MOTORS, LIFAN,
    ZONGSHEN, KEEWAY, KYMCO, HYOSUNG, RIEJU, URAL, MASH, CAGIVA, FANTIC, ARIEL, EXCELSIOR_HENDERSON, BORILE, MACBOR, INDIAN,
    BROUGH_SUPERIOR, SACHS, GREEVES, CLEVELAND_CYCLEWERKS, BIG_DOG_MOTORCYCLES, BOSS_HOSS;
}
