package org.example.proyectoprogramacion3fx.Model.vehiculos;

public enum MarcaVehiculoCarro {
    ALFA_ROMEO, AUDI, BMW, CITROEN, FIAT, HONDA, LEXUS, MAZDA, MERCEDES_BENZ,
    MITSUBISHI, OPEL, RENAULT, SEAT, SUBARU, TOYOTA, VOLKSWAGEN, VOLVO, ABARTH,
    MINI, DS, SUZUKI, HYUNDAI, SMART, DACIA, JAGUAR, MASERATI, PORSCHE, ASTON_MARTIN,
    BENTLEY, BYD, JEEP, LAND_ROVER, FERRARI, MORGAN, LAMBORGHINI, LOTUS, TESLA, SKODA,
    DODGE, MG, ISUZU, PEUGEOT, FORD, ALPINE, CUPRA, DFSK, DR, JIAYUAN, INVICTA,
    NISSAN, KIA, SSANGYONG, LYNK_CO, SWM, LEVC, AIWAYS, MAXUS, EVO, POLESTAR, INEOS,
    SERES, YUDO, OMODA, FISKER, CHEVROLET, RIMAC, BUGATTI, KOENIGSEGG, CADILLAC, HENNESSEY,
    LINCOLN, PAGANI, CORVETTE, ACURA, DAIHATSU, HUMMER, INFINITI, MCLAREN, RIVIAN, PONTIAC,
    ROLLS_ROYCE, SCION, PLYMOUTH, GMC, MAYBACH, NOBLE, LANCIA, APOLLO, GUMPERT, ARRIMERA,
    ARASH, ARTEGA, ASPARK,  BRILLIANCE, CHANGAN, CHERY, DARTZ, DETROIT_ELECTRIC, DONKERVOORT,
    EAGLE, ELARIS, EXAGON_MOTORS, FACEL_VEGA, FARBIO, GEELY, GILLET, GINETTA, HONGQI, JOSS,
    LIGIER, LUXGEN, MAHINDRA, MASTRETTA, MICROCAR, NIO, ORA, PANOZ, PERODUA, PROTON, QOROS,
    RIMAC_AUTOMOBILI, ROSSION, RUF, SAIC, SILK_FAW, SPYKER, TRAMONTANA, VINFAST, WEBER,
    XPENG, ZENOS, GREAT_WALL, EOLO, HAVAL, AC_CARS, AIXAM, ALVIS, ASPARK_OWL, ATLANTA_MOTORS,
    BOLLINGER, BRABHAM_AUTOMOTIVE, BYTON, CAPARO, CISITALIA, DAVID_BROWN_AUTOMOTIVE, ;
}
